# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Daniel Murphy
tagline:             'Sustainability Engineer, Carpenter, and Passivhaus Enthusiast'
description:         'Personal home pages'
url:                 https://danielkmurphy.github.io
#http://lanyon.getpoole.com
baseurl:             ''
#paginate:            
#no

# About/contact
author:
  name:              Daniel Murphy
  email:             dannymurphy365@gmail.com

# Custom vars
#version:             1.0.0

#theme: "ed."

theme: jekyll-theme-minimal
